### ISSUE TITLE
Me

### ISSUE THREAD

**Issue by malawrence1020** [NuttyTrains/NuttyTrains.github.io#9]
Am I doing something wrong? Every time you push an update, you have to merge my edits back into the master branch. What am I managing to do? XD

**Comment by jamesa9283** [comment]
I had a moment earlier today. I will sort it out.


Thanks, James AMathematical ProgrammerWeb Developerwww.JSites.co.uk
-------- Original message --------From: malawrence1020 <notifications@github.com> Date: 26/11/2019  14:20  (GMT+00:00) To: "NuttyTrains/NuttyTrains.github.io" <NuttyTrains.github.io@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [NuttyTrains/NuttyTrains.github.io] Me (#9) 
Am I doing something wrong? Every time you push an update, you have to merge my edits back into the master branch. What am I managing to do? XD

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/NuttyTrains/NuttyTrains.github.io/issues/9?email_source=notifications\u0026email_token=AF7A64URDQRSQHYV7FYFJDTQVUWEDA5CNFSM4JRYXPAKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H4EGDTQ",
"url": "https://github.com/NuttyTrains/NuttyTrains.github.io/issues/9?email_source=notifications\u0026email_token=AF7A64URDQRSQHYV7FYFJDTQVUWEDA5CNFSM4JRYXPAKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H4EGDTQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jamesa9283** [comment]
Ok, so just to note. It's not you, it's me. I run a local copy on my machine and so everytime I want to edit it, I have to pull it back to my machine and then push it back to the repository.
